--- 
- name: First Ansible Playbook  
  hosts: all
  remote_user: ubuntu
  become: true
  tasks:
    - name: update apt packages
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400
    - name: install python
      apt:
        name: python2.7
        state: installed
    - name: install latest version of nginx
      apt:
        name: nginx
        state: installed
    - name: install pip
      apt:
        name: python-pip
        state: latest
    - name: install pip3
      apt:
        name: python3-pip
        state: latest
    - name: install PrettyTable
      pip:
        name: PrettyTable
        state: present
    - name: install flask
      pip:
        name: flask
        state: present
    - name: install quik
      pip:
        name: quik
        state: present
    - name: install click
      pip:
        name: click
        state: present
    - name: copy nginx config file from local to server
      copy:
        src: /etc/nginx/sites-enabled/default
        dest: /etc/nginx/sites-enabled/default
    - name: restart nginx
      service:
        name: nginx
        state: restarted
    - name: pull down github files
      git:
        repo: "https://github.com/matt-twomey-iw/ateam_tt"
        dest: /home/ubuntu/miniProject
    - name: install flask
      shell: pip install flask
    - name: install quik
      shell: pip install quik
    - name: install PrettyTable
      shell: pip install PrettyTable
    - name: install click
      shell: pip install click
    - name: Start daemon
      shell: daemon -- FLASK_APP=/home/ubuntu/miniProject/table_tennis_ladder/table_tennis.py FLASK_DEBUG=1 python -m flask run &







